---
- name: Create Linode
  hosts: localhost
  vars_files:
      - ./vars.yml
      - ./group_vars/demo.yml
  tasks:
    - name: Destroy linodes
      linode_v4:
        label: "{{ item.label }}"
        access_token: "{{ linode_token }}"
        state: absent
      with_items: "{{ linodes }}"
        