
wireguard_address: 10.10.10.2
nats_address: "{{ wireguard_address }}"
nats_ansible_host_group: group_cluster_b

nats_gateway:
  name: 'B'
  ansible_host_groups:
    - group_cluster_a
    - group_cluster_b
