

wireguard_address: 10.10.10.1
nats_address: "{{ wireguard_address }}"
nats_ansible_host_group: group_gateway_a

nats_gateway:
  name: 'A'
  ansible_host_groups:
    - group_gateway_a
    - group_gateway_b

